#!/usr/bin/python
import sys
import os

def strFormat(filename):
    hfile = open(filename, "r")

if len(sys.argv) < 2:
    print sys.argv[0] + " [fileName]"
    sys.exit()

mfile = open(sys.argv[1], "w")

mfile.write("CC = gcc\nCFLAGS=-Wall -c\nLFLAGS=-Wall\nSRCDIR=/src/\nOBJDIR=/obj/\n\n")

for root, dirs, files in os.walk("./src"):
    for a in files:
        if a.find(".h") != -1:
            print a

mfile.close()
